services:
# page service
  webpage:
    build: ./page/
    hostname: website
    container_name: webpage
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - "../static/frontend/page/:/home/website/server/frontend"
  
  web:
    build: ./web/
    hostname: webpage
    container_name: web
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - "./web/src/:/home/web/src"
      - "./web/public/:/home/web/public"
      - "../static/:/home/web/static"

  jobs:
    build: ./jobs/
    hostname: machine_jobs
    container_name: jobs
    restart: always
    networks:
      - mainet
    volumes:
      - "../static/:/home/jobs/static"

  api_sessions:
    build: ./api/sessions
    hostname: api_sessions
    container_name: api_sessions
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - "../static/:/home/api_sessions/static/"

  api_users:
    build: ./api/users
    hostname: api_users
    container_name: api_users
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - "../static/:/home/api_users/static/"
  
  api_events:
    build: ./api/events
    hostname: api_events
    container_name: api_events
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - "../static/:/home/api_events/static/"

