services:
# page service
  webpage:
    build: ./page/
    hostname: website
    container_name: webpage
    networks:
      - mainet
    volumes:
      - "../static/frontend/page/:/home/website/server/frontend"
  
  web:
    build: ./web/
    hostname: webpage
    container_name: web
    networks:
      - mainet
    volumes:
      - "./web/src/:/home/web/src"
      - "./web/public/:/home/web/public"
      - "../static/:/home/web/static"

  api_service:
    build: ./api/
    hostname: api_service
    container_name: api_service
    networks:
      - mainet
