services:
# page service
  webpage:
    build: ./page/
    hostname: website
    networks:
      - mainet
    depends_on:
      - api_events
    volumes:
      - "../static/frontend/page/:/home/website/server/frontend"
  
# services
  api_events:
    build: ./api/events/
    hostname: api_events
    networks:
      - mainet
