include:
  - services/compose.yml
  - networks.yml

services:
  main:
    build: ./main/
    hostname: efserver
    restart: unless-stopped
    container_name: main
    networks:
      mainet:
        ipv4_address: 172.25.0.100
    volumes:
      - "./static/:/home/ef/static"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    container_name: mongodb
    hostname: mongodb
    networks:
      - mainet
    volumes:
      - /data/db

  redis_server:
    image: redis
    hostname: redis_server
    container_name: redis
    restart: unless-stopped
    networks:
      - mainet
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
