include:
  - services/compose.yml

services:
  main:
    build: ./main/
    hostname: efserver
    links:
      - services
      - webpage
    depends_on:
      - webpage
      - services

  webpage:
    build: ./website/
    hostname: website
