include:
  - services/compose.yml
  - networks.yml

services:
  main:
    build: ./main/
    hostname: efserver
    restart: unless-stopped
    container_name: main
    networks:
      - mainet
    depends_on:
      - redis_server
      - webpage
    volumes:
      - "./static/:/home/ef/static"

  redis_server:
    image: redis
    hostname: redis_server
    container_name: redis
    restart: unless-stopped
    networks:
      - mainet
